# -*- coding: utf-8 -*-
"""restuarant  bill calculator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SetA3ToR-T0ACJxN9aDXlvS84d6dUf3D
"""

## design a function that takes the##
    # #ordered items ,quantities, abd price to calculate##
    ##the total bill amount ##
    ##include options for applying discount,taxes, and splitting,the bill amon friends##


def resturantbill():

    item_inrestaurant=["biryani","chie","quorma","fries"]
    print(item_inrestaurant)
    print("ordered only above item")
    quantity1="biryani"
    price=250
    quantity2="quorma"
    price=700
    quantity3="chie"
    price=100
    quantity4="fries"
    price=80

    ordered_item=input("ordered the dishes you want to eat")
    quantity_item=int(input("enter the quantity: "))
    bill_perperson=int(input("enter the number of person which will pay bill "))
    discount_offer=int(input("enter the number of quantity item you purchase"))


    if ordered_item==quantity1:
        print(price)
        total_price=price*quantity_item
        print(total_price)
        print(total_price/bill_perperson)
        if discount_offer >= 12:
            print("congratulation for getting discount")
            print(total_price-100)
        else:
            print("you are not eligable for discount")
    elif ordered_item==quantity2:
        print(price)
        total_price=price*quantity_item
        print(total_price)
        print(total_price/bill_perperson)
        print(total_price)
        print(bill_perperson/total_price)
        if discount_offer >= 12:
            print("congratulation for getting discount")
            print(total_price-100)
        else:
            print("you are not eligable for discount")


    if ordered_item == quantity3:
        print(price)
        total_price=price*quantity_item
        print(total_price)
        print(total_price/bill_perperson)
        if discount_offer >= 12:
            print("congratulation for getting discount")
            print(total_price-100)
        else:
            print("you are not eligable for discount")



    if ordered_item == quantity4:
        print(price)
        total_price=price*quantity_item
        print(total_price)
        print(total_price/bill_perperson)

        print(price*quantity_item,"total price")
        print(total_price/bill_perperson)
        if discount_offer >= 12:
            print("congratulation for getting discount")
            print(total_price-100)
        else:
            print("you are not eligable for discount")

resturantbill()
resturantbill()
resturantbill()