# -*- coding: utf-8 -*-
"""travel cost estimator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PSzKUuopoAgaNW3mWpV-ZW475NbuRk3f
"""

#TRAVEL COST ESTIMATOR##
city1="karachi"
def karachi():
    print(karachi)
    ride1 = "car"
    ride2 = "train"
    ride3 = "bus"
    cost_of_car = 5000
    cost_of_train = 2000
    cost_of_bus = 1500
    livein = "hotel"
    livein1 = "hostel"
    hotel_per_night = 2000
    hostel_per_night = 500
city2="lahore"
def lahore():
    ride1 = "car"
    ride2 = "train"
    ride3="bus"
    cost_of_car=8500
    cost_of_train=6000
    cost_of_bus=1700
    livein="hotel"
    livein1="hostel"
    hotel_per_night=3000
    hostel_per_night=1000
city3="Islambad"
def Islambad():
    ride1 = "car"
    ride2 = "train"
    ride3="bus"
    print(ride1,ride2,ride3)
    cost_of_car=20000
    cost_of_train="that no train go direct Nawabshah to Islambad"
    cost_of_bus=2500
    print(cost_of_car,cost_of_train,cost_of_bus)
    live_hotel="hotel"
    live_hostel="hostel"
    print(live_hotel,live_hostel)
    hotel_per_night=3500
    hostel_per_night=1500
    print(hotel_per_night,hostel_per_night)


destination=(input("where you go "))
travelling_type=(input("enter the transportation in which you travel"))
accomodation=input("give idea in where you want to live hotel od hostel")
if destination == city1:
    karachi()

elif destination == city2:
    lahore()
elif destination == city3:
    Islambad()
elif travelling_type == ride1:
    print(cost_of_car)